package models

import "time"

type PromotionItem struct {
	PRI_KEY                            int `gorm:"primaryKey"`
	PRI_USR                            int
	PRI_FILE_ORG                       string
	PRI_FILE_NEW                       string
	PRI_NO                             string
	PRI_STORE_FORMAT                   string
	PRI_STORE_TYPE                     string
	PRI_START_DATE                     string
	PRI_START_TIME                     string
	PRI_END_DATE                       string
	PRI_END_TIME                       string
	PRI_TOTAL_DAY                      string
	PRI_ITEM_CODE                      string
	PRI_ITEM_NAME                      string
	PRI_AMOUNT_UNIT_1                  string
	PRI_AMOUNT_UNIT_2                  string
	PRI_AMOUNT_UNIT_3                  string
	PRI_AMOUNT_UNIT                    string
	PRI_BARCODE                        string
	PRI_UNIT                           string
	PRI_CATEGORY_CODE                  string
	PRI_CATEGORY_NAME                  string
	PRI_SUPPLIER_CODE                  string
	PRI_SUPPLIER_NAME                  string
	PRI_ITEM_GRADE                     string
	PRI_ITEM_STATUS                    string
	PRI_PROMOTION_CODE                 string
	PRI_PROMOTION_TYPE                 string
	PRI_PROMOTION_INFO                 string
	PRI_SURPRISE_SALE                  string
	PRI_COST_TYPE                      string
	PRI_COST_BEFORE                    string
	PRI_COST_PROMOTION                 string
	PRI_COST_START_DATE                string
	PRI_PRICE_BEFORE_PROMOTION         string
	PRI_PRICE_PROMOTION                string
	PRI_PRICE_MEMBER                   string
	PRI_PRICE_MARKET                   string
	PRI_COMPENSATE                     string
	PRI_COMPENSATE_PER_ITEM            string
	PRI_COMPENSATE_MEMBER              string
	PRI_COMPENSATE_UNIT                string
	PRI_COMPENSATE_CLAIM               string
	PRI_GP_PERCENT                     string
	PRI_GP_PERCENT_PROMOTION           string
	PRI_GP_PERCENT_MEMBER              string
	PRI_MAIL_FEE                       string
	PRI_FLAG_BADGE                     string
	PRI_FLAG_ON_PACK                   string
	PRI_FLAG_HEAD                      string
	PRI_FLAG_BUY                       string
	PRI_FLAG_RELEASE                   string
	PRI_FORECAST_SALE                  string
	PRI_FORECAST_PURCHASE              string
	PRI_REMARK                         string
	PRI_QUOTA_PURCHASE                 string
	PRI_QUOTA_SALE                     string
	PRI_RANK                           string
	PRI_PRO_FORECAST_BAHT              string
	PRI_NO_OF_STORE                    string
	PRI_DIVISION_CODE                  string
	PRI_TOTAL_AMOUNT                   string
	PRI_TOTAL_VALUE                    string
	PRI_OTHER_1                        string
	PRI_OTHER_2                        string
	PRI_OTHER_3                        string
	PRI_OTHER_4                        string
	PRI_FREE_ITEM_FLAG                 string
	PRI_FREE_ITEM_TOTAL                string
	PRI_FREE_ITEM_1_CODE               string
	PRI_FREE_ITEM_1_UNIT               string
	PRI_FREE_ITEM_2_CODE               string
	PRI_FREE_ITEM_2_UNIT               string
	PRI_FREE_ITEM_3_CODE               string
	PRI_FREE_ITEM_3_UNIT               string
	PRI_THEME_CODE                     string
	PRI_THEME_NAME                     string
	PRI_PROMOTION_POS                  string
	PRI_ALL_SITE                       string
	PRI_SITE_GROUP                     string
	PRI_EXCEPT_GROUP                   string
	PRI_EFFECTIVE_TIME                 string
	PRI_EFFECTIVE_START_TIME           string
	PRI_EFFECTIVE_END_TIME             string
	PRI_EFFECTIVE_MO                   string
	PRI_EFFECTIVE_TU                   string
	PRI_EFFECTIVE_WE                   string
	PRI_EFFECTIVE_TH                   string
	PRI_EFFECTIVE_FR                   string
	PRI_EFFECTIVE_SA                   string
	PRI_EFFECTIVE_SU                   string
	PRI_LIMIT_SET                      string
	PRI_LIMIT_DISCOUNT                 string
	PRI_LIMIT_POINT                    string
	PRI_OPTION_1                       string
	PRI_OPTION_2                       string
	PRI_OPTION_3                       string
	PRI_OPTION_4                       string
	PRI_MEMBER_FLAG                    string
	PRI_MEMBER_NO                      string
	PRI_MEMBER_GROUP                   string
	PRI_MEMBER_LEVEL                   string
	PRI_COMBINE_FLAG                   string
	PRI_COMBINE_VALUE                  string
	PRI_COMBINE_POINT                  string
	PRI_STEP_FLAG                      string
	PRI_STEP_NO                        string
	PRI_STEP_PERIOD                    string
	PRI_STEP1_START                    string
	PRI_STEP1_END                      string
	PRI_STEP1_TYPE                     string
	PRI_STEP1_VALUE                    string
	PRI_STEP1_VALUE_TOTAL              string
	PRI_STEP1_PERCENT_WEIGHT           string
	PRI_STEP1_GET_POINT                string
	PRI_STEP1_GET_POINT_TYPE           string
	PRI_STEP2_START                    string
	PRI_STEP2_END                      string
	PRI_STEP2_TYPE                     string
	PRI_STEP2_VALUE                    string
	PRI_STEP2_VALUE_TOTAL              string
	PRI_STEP2_PERCENT_WEIGHT           string
	PRI_STEP2_GET_POINT                string
	PRI_STEP2_GET_POINT_TYPE           string
	PRI_STEP3_START                    string
	PRI_STEP3_END                      string
	PRI_STEP3_TYPE                     string
	PRI_STEP3_VALUE                    string
	PRI_STEP3_VALUE_TOTAL              string
	PRI_STEP3_PERCENT_WEIGHT           string
	PRI_STEP3_GET_POINT                string
	PRI_STEP3_GET_POINT_TYPE           string
	PRI_STEP4_START                    string
	PRI_STEP4_END                      string
	PRI_STEP4_TYPE                     string
	PRI_STEP4_VALUE                    string
	PRI_STEP4_VALUE_TOTAL              string
	PRI_STEP4_PERCENT_WEIGHT           string
	PRI_STEP4_GET_POINT                string
	PRI_STEP4_GET_POINT_TYPE           string
	PRI_STEP5_START                    string
	PRI_STEP5_END                      string
	PRI_STEP5_TYPE                     string
	PRI_STEP5_VALUE                    string
	PRI_STEP5_VALUE_TOTAL              string
	PRI_STEP5_PERCENT_WEIGHT           string
	PRI_STEP5_GET_POINT                string
	PRI_STEP5_GET_POINT_TYPE           string
	PRI_GET_POINT_FLAG                 string
	PRI_GET_POINT_VALUE                string
	PRI_GET_POINT_TYPE                 string
	PRI_PROMO2_FLAG                    string
	PRI_PROMO2_ITEM_CODE               string
	PRI_PROMO2_ITEM_NAME               string
	PRI_PROMO2_UNIT                    string
	PRI_PROMO2_ITEM1_WEIGHT            string
	PRI_PROMO2_ITEM2_WEIGHT            string
	PRI_ITEM_GROUP_CODE                string
	PRI_ITEM_GROUP_NAME                string
	PRI_ITEM_CREATE_USER               string
	PRI_ITEM_CREATE_DATE               string
	PRI_PROMOTION_ID                   string
	PRI_PROMOTION_CREATE_USER          string
	PRI_PROMOTION_CREATE_DATE          time.Time `gorm:"column:PRI_PROMOTION_CREATE_DATE"`
	PRI_PROMOTION_APPROVE_USER         string
	PRI_PROMOTION_APPROVE_DATE         string
	PRI_FREE_ARTICLE_GROUP             string
	PRI_STEP1_FREE_ARTICLE_GROUP       string
	PRI_STEP2_FREE_ARTICLE_GROUP       string
	PRI_STEP3_FREE_ARTICLE_GROUP       string
	PRI_STEP4_FREE_ARTICLE_GROUP       string
	PRI_STEP5_FREE_ARTICLE_GROUP       string
	PRI_STEP1_FREE_ARTICLE_GROUP_TOTAL string
	PRI_STEP2_FREE_ARTICLE_GROUP_TOTAL string
	PRI_STEP3_FREE_ARTICLE_GROUP_TOTAL string
	PRI_STEP4_FREE_ARTICLE_GROUP_TOTAL string
	PRI_STEP5_FREE_ARTICLE_GROUP_TOTAL string
	PRI_COUPON_ITEM_FLAG               string
	PRI_COUPON_ITEM_TOTAL              string
	PRI_COUPON_ITEM_1_CODE             string
	PRI_COUPON_ITEM_2_CODE             string
	PRI_COUPON_ITEM_3_CODE             string
	PRI_COUPON_ITEM_1_UNIT             string
	PRI_COUPON_ITEM_2_UNIT             string
	PRI_COUPON_ITEM_3_UNIT             string
	PRI_COUPON_ARTICLE_GROUP           string
	PRI_MEMBER_TYPE                    string
	PRI_UNIT_MAPPING                   string
	PRI_PROMO2_ARTICLE_GROUP1          string
	PRI_PROMO2_ARTICLE_GROUP2          string
	PRI_PROMOTION_MEM                  string
	PRI_STEP1_ARTICLE_GROUP            string
	PRI_STEP2_ARTICLE_GROUP            string
	PRI_STEP3_ARTICLE_GROUP            string
	PRI_STEP4_ARTICLE_GROUP            string
	PRI_STEP5_ARTICLE_GROUP            string
	PRI_PROMOTION_ID_2                 string
	PRI_DRAFT_ID                       string
	PRI_PROMOTION_NAME                 string
	PRI_STATUS                         int
	PRI_INST_USER                      string
	PRI_INST_DATE                      time.Time `gorm:"column:PRI_INST_DATE"`
	PRI_UPDT_USER                      string
	PRI_UPDT_DATE                      time.Time `gorm:"column:PRI_UPDT_DATE"`
	PRI_BUYER_CREATE_BY                int
	PRI_BUYER_CREATE_BY1               int
	PRI_BUYER_CREATE_DATE              time.Time `gorm:"column:PRI_BUYER_CREATE_DATE"`
	PRI_BUYER_APPROVE_BY               int
	PRI_BUYER_APPROVE_DATE             time.Time `gorm:"column:PRI_BUYER_APPROVE_DATE"`
	PRI_BUYER_REJECT1_DATE             time.Time `gorm:"column:PRI_BUYER_REJECT1_DATE"`
	PRI_BUYER_REJECT1_REMARK           string
	PRI_BUYER_TIME_NO                  int
	PRI_BUYER_TIME_SEQ                 int
	PRI_BUYER_TIME_GROUP               string
	PRI_TRADE_REVIEW_BY                int
	PRI_TRADE_REVIEW_DATE              time.Time `gorm:"column:PRI_TRADE_REVIEW_DATE"`
	PRI_TRADE_APPROVE_BY               int
	PRI_TRADE_APPROVE_DATE             time.Time `gorm:"column:PRI_TRADE_APPROVE_DATE"`
	PRI_TRADE_REJECT1_DATE             time.Time `gorm:"column:PRI_TRADE_REJECT1_DATE"`
	PRI_TRADE_REJECT2_DATE             time.Time `gorm:"column:PRI_TRADE_REJECT2_DATE"`
	PRI_TRADE_REJECT1_REMARK           string
	PRI_TRADE_REJECT2_REMARK           string
	PRI_DATA_GROUP_BY                  int
	PRI_DATA_GROUP_DATE                time.Time `gorm:"column:PRI_DATA_GROUP_DATE"`
	PRI_DATA_APPROVE_BY                int
	PRI_DATA_APPROVE_DATE              time.Time `gorm:"column:PRI_DATA_APPROVE_DATE"`
	PRI_DATA_REJECT1_DATE              time.Time `gorm:"column:PRI_DATA_REJECT1_DATE"`
	PRI_DATA_REJECT2_DATE              time.Time `gorm:"column:PRI_DATA_REJECT2_DATE"`
	PRI_DATA_REJECT1_REMARK            string
	PRI_DATA_REJECT2_REMARK            string
	PRI_CANCEL_BY                      int
	PRI_CANCEL_DATE                    string
	PRI_CANCEL_REMARK                  string
	PRI_ROUND_NO                       int
	PRI_ROUND_GROUP                    string
	PRI_ROUND_SEQ                      string
	PRI_ROUND_DESC                     string
	PRI_REF_ID                         string
	PRI_THEME_KEY                      int
	PRI_PERIOD_KEY                     int
	PRI_TOTAL_BRANCH                   string
	PRI_PERIOD_NAME                    string
	PRI_BUYER_REMARK                   string
	PRI_TRADE_REMARK                   string
	PRI_DATA_REMARK                    string
	PRI_REF_NAME                       string
	PRI_PROMOTION_DESC                 string
	PRI_BRANCH_DESC                    string
	PRI_COMPENSATE_MEMBER_PER_ITEM     string
	PRI_PRICE_BEFORE_CHANGE            string
	PRI_COMPLETE_REMARK                string
	PRI_COMPLETE_OWNER                 string
	PRI_COMPLETE_OWNER_OTHER           string
	PRI_COMPLETE_FILE_REF              string
	PRI_COPY_REMARK                    string
	PRI_COPY_OWNER                     string
	PRI_COPY_OWNER_OTHER               string
	PRI_COPY_FILE_REF                  string
	PRI_COPY_THEME_KEY                 int
	PRI_COPY_PERIOD_KEY                int
	PRI_COPY_BRANCH_DESC               string
	PRI_LIMIT_SET_PER_BILL             string
	PRI_PRICE_PROMOTION_PERCENT        string
	PRI_PRICE_PROMOTION_TYPE           string
	PRI_STEP1_COMPENSATE               string
	PRI_STEP2_COMPENSATE               string
	PRI_STEP3_COMPENSATE               string
	PRI_STEP4_COMPENSATE               string
	PRI_STEP5_COMPENSATE               string
	PRI_FEE_FLAG_MEDIA                 string
	PRI_FEE_PAYMENT_METHOD             string
	PRI_FEE_MEDIA_COST                 string
	PRI_FEE_CLAIM_NO                   string
}

func (PromotionItem) TableName() string {
	return "tab_promotion_item"
}
